.PHONY: ramb64x1_tb
ramb64x1_tb:
	xelab --prj prj/ramb64x1_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.ramb64x1_tb

.PHONY: ramb64x8_tb
ramb64x8_tb:
	xelab --prj prj/ramb64x8_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.ramb64x8_tb

